services:
  db:
    image: postgres:15
    container_name: postgres_authentification_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: authentification_db
    ports:
      - "5440:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - authentification-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentification_app
    depends_on:
      - db
    ports:
      - "9086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authentification_db
    networks:
      - authentification-net

volumes:
  db-data:

networks:
  authentification-net:
